#!/run/current-system/sw/bin/lua

local config_dir = os.getenv("CONFIG_DIR") or (os.getenv("HOME") .. "/.config/sketchybar")

package.path = table.concat({
  config_dir .. "/?.lua",
  config_dir .. "/?/init.lua",
  "/run/current-system/sw/lib/sketchybar-app-font/?.lua",
  "/run/current-system/sw/share/lua/5.5/?.lua",
  "/run/current-system/sw/share/lua/5.5/?/init.lua",
  "/run/current-system/sw/share/lua/5.4/?.lua",
  "/run/current-system/sw/share/lua/5.4/?/init.lua",
  package.path,
}, ";")

package.cpath = table.concat({
  "/run/current-system/sw/lib/lua/5.5/?.so",
  "/run/current-system/sw/lib/lua/5.4/?.so",
  package.cpath,
}, ";")

require("init")
